public class SampleClass 
{
    //Variables
    

    // Method #1 - to print name
    public void printName() {
        System.debug('Rajesh');
    }

    // Method #2 - to print name
    // takes strname as an input argumment and shows the name in the output   
    public void ShowName(String strname) 
    
    {
        System.debug('Your name is ' + strname);
    }

    // Method #3 - to print name & desination
    // takes strname as an input argumment and shows the name in the output   
    public void ShowUserProfile(String strname, String strDesgination) 
    
    {
        System.debug('Your name is ' + strname + ' and your designation is ' + strDesgination);
    }  
    

}
    
    
